### ISSUE TITLE
Wondering if you could do a runewizard for a new Diablo 2 Resurrected Mod

### ISSUE THREAD

**Issue by Vphrism** [fabd/diablo2-runewizard#45]

**Comment by Vphrism** [comment]
https://www.d2r-reimagined.com/runewords

About 170 KEKW

**Comment by fabd** [comment]
Sorry I don't have the motivation to do it myself - the best I could do is make the project re-usable as I did with this repo. Someone with medium level Javascript knowledge can compile the repo, someone with just editing skills could edit `runewords.ts` and put all the new runewords. But yeah it's a bit of work.

For example kvothed forked and put in the runewords for Project Diablo 2 https://kvothed2.github.io/pd2-runewizard/
